<template>
  <!-- 菜单栏弹窗 -->
  <uni-popup ref="popup" background-color="rgba(0, 0, 0, 0)" @change="change" class="popup">
    <view class="popup-content" :class="{ 'popup-height': type === 'left' || type === 'right' }">Hello</view>
  </uni-popup>
  <!-- 分享栏弹窗 -->
  <uni-popup ref="share" type="share" safeArea backgroundColor="#fff">
    <uni-popup-share></uni-popup-share>
  </uni-popup>
  <!-- 可见文档流主体 -->
  <view class="content colcenter">
    <view class="loader"></view>
    <view class="header borderbox rowleft">
      <view class="menu-button center tinyradius ml">
        <uni-icons :type="backIcon" size="20" color="#909399"></uni-icons>
      </view>
      <view class="menu-button center tinyradius ml" @click="toggle('left')">
        <uni-icons type="bars" size="20" color="#909399"></uni-icons>
      </view>
      <view class="header-title ml2 smallfont infofont">
        {{ title }}
      </view>
      <view class="active-button circleradius center" :class="{ activate: isActive }" @click="handleActivate">
        <view class="inner-active-button circleradius"></view>
      </view>
    </view>
  </view>
</template>

<script>
export default {
  props: {
    title: {
      type: String,
      default: '导航栏'
    },
    isHome: {
      type: Boolean,
      default: false
    }
  },
  data() {
    return {
      type: 'left',
      isActive: false,
      backIcon: 'undo-filled',
      menuList: []
    };
  },
  methods: {
    handleActivate() {
      this.isActive = true;
      this.shareToggle();
      setTimeout(() => {
        this.isActive = false;
      }, 800);
    },
    change(e) {
      console.log('当前模式：' + e.type + ',状态：' + e.show);
    },
    toggle(type) {
      this.type = type;
      // open 方法传入参数 等同在 uni-popup 组件上绑定 type属性
      this.$refs.popup.open(type);
    },
    shareToggle() {
      this.$refs.share.open();
    }
  },
  mounted() {
    if (this.isHome === true) {
      this.backIcon = 'home-filled';
    }
  }
};
</script>

<style scoped>
@import '../../static/css/global.scss';

.content {
  height: 105rpx;
  width: 100%;
  position: fixed;
  z-index: 2000;
}
.loader {
  height: 5rpx;
  width: 100%;
  background-color: #3091ff;
}
.header {
  height: 100rpx;
  width: 100%;
  overflow: hidden;
  background-color: #fbfbfb;
  border-bottom: 1px solid #ddd;
}
.menu-button {
  border: 1px solid #ddd;
  height: 50rpx;
  width: 50rpx;
  padding: 5rpx;
}
.active-button {
  position: absolute;
  height: 60rpx;
  width: 60rpx;
  right: 20rpx;
  background-color: #abcaff;
}
.inner-active-button {
  height: 34rpx;
  width: 34rpx;
  background-color: #005eff;
}

.active-button.activate {
  -webkit-animation: ping 0.8s ease-in-out infinite both;
  animation: ping 0.8s ease-in-out infinite both;
}

.popup {
  z-index: 7000;
}

.popup-content {
  width: 600rpx;
  height: 100%;
  border-top-right-radius: 20rpx;
  border-bottom-right-radius: 20rpx;
  background-color: #fff;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-8-24 15:49:21
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation ping
 * ----------------------------------------
 */
@-webkit-keyframes ping {
  0% {
    -webkit-transform: scale(0.2);
    transform: scale(0.2);
    opacity: 0.8;
  }
  80% {
    -webkit-transform: scale(1.2);
    transform: scale(1.2);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(2.2);
    transform: scale(2.2);
    opacity: 0;
  }
}
@keyframes ping {
  0% {
    -webkit-transform: scale(0.2);
    transform: scale(0.2);
    opacity: 0.8;
  }
  80% {
    -webkit-transform: scale(1.2);
    transform: scale(1.2);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(2.2);
    transform: scale(2.2);
    opacity: 0;
  }
}
</style>
